import { Project } from "@/types/project";


export const projects: Project[] = [
  {
    id: "1",
    title: "Collaborative Project Platform",
    description:
      "Building a platform to connect talented individuals with exciting collaborative projects across various domains.",
    skills: ["react", "node_js", "typescript", "postgresql"],
    teamSize: "Medium (6-10)",
    timeline: "Medium-term (3-6 months)",
    openPositions: 3,
    status: "Hot",
    techStack: ["react", "node_js", "typescript", "postgresql"],
    category: "web_app",
    stage: "Development",
    ecosystem: "web",
  },
  {
    id: "2",
    title: "AI-Powered Content Generator",
    description:
      "Developing an AI tool that helps creators generate high-quality content ideas and outlines based on trending topics.",
    skills: ["python", "ai_ml", "next_js", "typescript"],
    teamSize: "Small (2-5)",
    timeline: "Long-term (6+ months)",
    openPositions: 2,
    techStack: ["python", "next_js", "typescript"],
    category: "ai_ml",
    stage: "Planning",
    ecosystem: "ai_ml",
  },
  {
    id: "3",
    title: "Sustainable E-commerce Platform",
    description:
      "Creating an e-commerce platform focused on sustainable and eco-friendly products with carbon footprint tracking.",
    skills: ["react", "node_js", "mongodb", "tailwind"],
    teamSize: "Medium (6-10)",
    timeline: "Medium-term (3-6 months)",
    openPositions: 4,
    status: "New",
    techStack: ["react", "node_js", "mongodb", "tailwind"],
    category: "web_app",
    stage: "Idea",
    ecosystem: "web",
  },
  {
    id: "4",
    title: "Educational Mobile App for Kids",
    description:
      "Building a fun and interactive mobile app that helps children learn basic programming concepts through games.",
    skills: ["react_native", "typescript", "firebase", "ui_ux"],
    teamSize: "Small (2-5)",
    timeline: "Short-term (< 3 months)",
    openPositions: 2,
    techStack: ["react_native", "typescript", "firebase"],
    category: "mobile_app",
    stage: "Development",
    ecosystem: "mobile",
  },
  {
    id: "5",
    title: "Community-Driven Podcast Platform",
    description: "Developing a platform where communities can create, share, and discover podcasts on niche topics.",
    skills: ["vue", "node_js", "aws", "mongodb"],
    teamSize: "Small (2-5)",
    timeline: "Medium-term (3-6 months)",
    openPositions: 3,
    techStack: ["vue", "node_js", "aws", "mongodb"],
    category: "web_app",
    stage: "Testing",
    ecosystem: "web",
  },
  {
    id: "6",
    title: "Blockchain-Based Voting System",
    description:
      "Creating a secure and transparent voting system using blockchain technology for organizations and communities.",
    skills: ["blockchain", "solidity", "react", "node_js"],
    teamSize: "Medium (6-10)",
    timeline: "Long-term (6+ months)",
    openPositions: 5,
    status: "Ending Soon",
    techStack: ["blockchain", "solidity", "react", "node_js"],
    category: "blockchain",
    stage: "Development",
    ecosystem: "blockchain",
  },
]
